beckermr/pizza-cutter

.circleci/config.yml
pizza_cutter/des_coadd_data.py
pizza_cutter/files.py
pizza_cutter/tests/test_des_coadd_data.py
pizza_cutter/tests/test_integration.py
requirements.txt

This PR pulls out the relevant code for dealing with DESDM.

ENH added first pass at classes for coadds and sources

---

.circleci/config.yml
.gitignore
README.md
bin/coadd-sim-pizza-cutter
config_files/cmc-griz-005-flat.yaml
pizza_cutter/coadd_sim_slicer/slicer.py
pizza_cutter/coadd_sim_slicer/tests/test_slicer.py
requirements.txt
setup.py

This PR has a working version of code to make "pizza slice" MEDS files for metadetection from the Niall's deblending sims for DES.
To do:

ENH make slices from deblend sims

---

pizza_cutter/coadd_sim_slicer/tests/test_slicer.py

TST finished the tests

---

bin/coadd-sim-pizza-cutter
config_files/cmc-griz-005-flat.yaml
requirements.txt

This PR switches to jinja2 for templates.

ENH use jinja2 for templates

---

pizza_cutter/des_pizza_cutter/_sky_bounds.py
pizza_cutter/des_pizza_cutter/_slice_data.py
pizza_cutter/des_pizza_cutter/_slice_flagging.py
pizza_cutter/des_pizza_cutter/tests/test_sky_bounds.py
pizza_cutter/des_pizza_cutter/tests/test_slice_data.py
pizza_cutter/des_pizza_cutter/tests/test_slice_flagging.py

This PR adds functions for making pizza slices.

ENH DES pizza slices

---

pizza_cutter/des_pizza_cutter/_slice_data.py
pizza_cutter/des_pizza_cutter/tests/test_slice_data.py

This PR has a faster interpolation algorithm.

PERF faster interpolation

---

pizza_cutter/des_pizza_cutter/_slice_flagging.py
pizza_cutter/des_pizza_cutter/tests/test_slice_flagging.py

This PR adds a function to flag unmasked bleed trails.

ENH add flagging for unmasked bleed trails

---

bin/run-metadetect-on-coadd-sim
bin/run-metadetect-on-slices
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/coadd_sim_slicer/memmappednoise.py
pizza_cutter/coadd_sim_slicer/slicer.py
pizza_cutter/metadetect/run_metadetect.py
setup.py

This PR has code to slice coadd sims on-the-fly. It should make the overall sims more efficient.

ENH slice coadd sims on the fly

---

bin/coadd-sim-pizza-cutter
bin/run-metadetect-on-coadd-sim
bin/run-metadetect-on-slices
config_files/metadetect.yaml
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/coadd_sim_slicer/slicer.py
pizza_cutter/coadd_sim_slicer/tests/test_medsreader.py
pizza_cutter/coadd_sim_slicer/tests/test_memmappednoise.py
pizza_cutter/files.py
pizza_cutter/metadetect/run_metadetect.py
pizza_cutter/metadetect/tests/test_get_part_ranges.py

This PR adds file staging for work at BNL.

ENH add file staging, processing of chunks

---

pizza_cutter/coadd_sim_slicer/galsim_psf.py
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/coadd_sim_slicer/slicer.py
pizza_cutter/coadd_sim_slicer/tests/test_galsimpsf.py
pizza_cutter/coadd_sim_slicer/tests/test_medsreader.py
pizza_cutter/coadd_sim_slicer/tests/test_slicer.py

This PR adds code to handle galsim PSFs.

ENH handle galsim PSFs

---

bin/des-pizza-cutter
pizza_cutter/simulation/des_masks.py
pizza_cutter/simulation/maskgen.py
pizza_cutter/simulation/tests/test_des_masks.py
pizza_cutter/simulation/tests/test_maskgen.py
scripts/gen_des_y3_bit_mask_catalog.py

This PR has code to generate and apply random bit masks from SE images to the coadd sims.

ENH code to produce masks from a catalog

---

pizza_cutter/coadd_sim_slicer/galsim_psf.py
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/coadd_sim_slicer/tests/test_galsimpsf.py
pizza_cutter/coadd_sim_slicer/tests/test_medsreader.py

This PR moves the code to use galsim to read PSFEx files.

ENH use GalSim to read PSFEx files

---

pizza_cutter/coadd_sim_slicer/galsim_psf.py
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/coadd_sim_slicer/tests/test_galsimpsf.py
pizza_cutter/metadetect/tests/test_metadetect.py

This PR adds some galsim-like parsing to let us do simple varying PSFs for the sims. I could not figure out how to use the builtin galsim parser to get this done, so here I am.
@rmjarvis @esheldon for viz

ENH more galsim stuff

---

.circleci/config.yml
bin/des-pizza-cutter
bin/run-metadetect-on-coadd-sim
bin/run-metadetect-on-slices
pizza_cutter/files.py
requirements.txt

mark required opts

---

bin/des-pizza-cutter
config_files/des-pizza-slices.yaml
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

modified the config also to have info needed for the downloader
(source_type), so we can use this same config for both

don't download here

---

pizza_cutter/des_pizza_cutter/__init__.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

DOC added docs

---

pizza_cutter/des_pizza_cutter/_se_image.py

This PR adds caching of the noise images. 
Closes #59 
@esheldon this should reduce the calls to `normal` in your profiling.

add caching for noise images

---

pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

This PR fixes a bug in properly seeding the RNG for the noise images.

fixed bug in RNG for noise images

---

pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_inverse.py

added test for pixmappy inverses

---

pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/conftest.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_inverse.py

This PR has a test for scamp.
Closes #65

enable fast inverse for scamp

---

bin/des-pizza-cutter
config_files/des-pizza-slices.yaml
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_ccd_bnds.py

add edge buffer and tests

---

pizza_cutter/slice_utils/interpolate.py
pizza_cutter/slice_utils/tests/test_interpolate.py

closes #64 
Is a buffer of size 3 enough? 
Do we need better tests of this for a more
realistic case?

select +/- 3 rows and cols for interpolation

---

pizza_cutter/coadd_sim_slicer/mask_sim.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/slice_utils/symmetrize.py
pizza_cutter/slice_utils/tests/test_symmetrize.py

symmetrize all the bits

---

config_files/des-pizza-slices-y5.yaml
config_files/des-pizza-slices.yaml

Lower threshold

---

pizza_cutter/des_pizza_cutter/_pizza_cutter.py

adding nepoch to object_data

---

pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

More epochs info

---

pizza_cutter/coadd_sim_slicer/mask_sim.py
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/memmappednoise.py
pizza_cutter/tests/test_memmappednoise.py

This PR gets the last (hopefully) of the cases where the max weight was not used.
Closes #82 
Closes #91

use max weight and non-int sizes

---

pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_ccd_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_set_psf.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_sky_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_slice_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_inverse.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_jacobian.py

This PR removes the image size constraints from the code to prep for sims.
Closes #90

remove image size constraints

---

bin/des-pizza-cutter
bin/des-pizza-cutter-prep-tile
config_files/des-pizza-slices-y3.yaml
config_files/des-pizza-slices-y5.yaml
pizza_cutter/des_pizza_cutter/__init__.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_constants.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py

This PR makes it easier to add configuration options and centralizes some of the bit mask handling that should have already been centralized.
Closes #102

ENH improve config handling

---

pizza_cutter/des_pizza_cutter/_load_info.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

expandvars in paths as needed, save in meds files

---

.circleci/config.yml
pizza_cutter/des_pizza_cutter/_affine_wcs.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_load_info.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/_sky_bounds.py
pizza_cutter/des_pizza_cutter/tests/test_affine_wcs.py
pizza_cutter/des_pizza_cutter/tests/test_build_gsobject.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_ccd_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_set_psf.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_sky_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_slice_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_slice_io.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_jacobian.py
pizza_cutter/des_pizza_cutter/tests/test_sky_bounds_affine.py
requirements.txt
volatile-requirements.txt

This PR adds the ability to use a general affine WCS for simulations.
Closes #87 
Closes #104 
Closes #122

ENH enable affine WCS for sims

---

pizza_cutter/metadetect/run_metadetect.py

closes #125 
turns out the issue wasn't None for the mbobs, but lenght zero ObsList i

check for cases without any image available

---

bin/run-metadetect-on-slices
pizza_cutter/metadetect/run_metadetect.py

enable specific ranges

---

pizza_cutter/coadding/_lanczos.py
pizza_cutter/coadding/tests/test_lanczos.py
pizza_cutter/des_pizza_cutter/_se_image.py

PERF speed up single lanczos func

---

pizza_cutter/coadding/tests/test_lanczos_two.py

tests for resampling two

---

pizza_cutter/des_pizza_cutter/_piff_tools.py

closes #97 
turns out some were left out of the piff run, so just
skip for now.  they should be rare

skip over missing piff exposures

---

pizza_cutter/des_pizza_cutter/_load_info.py

This PR coerces all image shapes to tuples.

ENH coerce to tuples for caching

---

pizza_cutter/des_pizza_cutter/_des_info.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py

use tuples for shapes so we can hash them

---

pizza_cutter/metadetect/run_metadetect.py
pizza_cutter/metadetect/tests/test_run_metadetect.py

closes #146 
it was being called simply id before

store slice_id

---

bin/run-metadetect-on-slices

if sending --range use range in filename

---

pizza_cutter/metadetect/run_metadetect.py
pizza_cutter/metadetect/tests/test_metadetect.py
pizza_cutter/metadetect/tests/test_run_metadetect.py

closes #150 
requires updates in metadetect to include the unsheared row, col
also updated the unit tests and made keyword argument names
consistent for slice_id

add unsheared ra,dec

---

bin/run-metadetect-on-slices

closes #158 
I also simplified the output file name, it was getting too long

fix bug when part/range not sent.  simplify names

---

pizza_cutter/des_pizza_cutter/_se_image.py

set c=0 explicitly in _radec calls for pixmappy

---

bin/run-metadetect-on-slices
pizza_cutter/metadetect/run_metadetect.py

so make_output_filename can be used outside the package

put some funcs from script in run_metadetect

---

bin/run-metadetect-on-slices
pizza_cutter/files.py

copy meds files to tmpdir to avoid seeks on gpfs

---

.circleci/config.yml
dev-requirements.txt
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/coadd_sim_slicer/tests/test_mask_sim.py
pizza_cutter/coadding/tests/test_wcs_utils.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/conftest.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_inverse.py
pizza_cutter/tests/test_memmappednoise.py
requirements.txt
setup.cfg
volatile-requirements.txt

TST fix the tests

---

config_files/metadetect.yaml
pizza_cutter/coadd_sim_slicer/medsreader.py
pizza_cutter/des_pizza_cutter/_constants.py

DEP do not use 2**30 ask a flag value

---

pizza_cutter/coadding/__init__.py
pizza_cutter/coadding/_lanczos.py
pizza_cutter/coadding/_wcs_utils.py
pizza_cutter/coadding/tests/test_wcs_utils.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/integration_test/data.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_pixel_area.py

This PR adds coadding in surface brightness units.

ENH coadd with pixel scales

---

pizza_cutter/coadding/_lanczos.py
pizza_cutter/coadding/tests/test_lanczos.py
pizza_cutter/coadding/tests/test_lanczos_two.py
scripts_and_notebooks/time_sinc_pade.ipynb

It is not clear this optimization helps a whole lot at least for the test suite. It might in real analysis.
Closes #171

PERF faster lanczos interp function

---

README.md
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py

Set PIFF psf size to 25.
This might be too small still, but it is a start

Piff stamp size

---

pizza_cutter/slice_utils/pbar.py

Trying to make this a bit easier to use.

REF send pbar to stdout

---

bin/des-pizza-cutter-prep-tile
config_files/des-pizza-slices-y6.yaml
pizza_cutter/des_pizza_cutter/_affine_wcs.py
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_load_info.py
pizza_cutter/des_pizza_cutter/_piff_tools.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/integration_test/data.py
pizza_cutter/des_pizza_cutter/tests/test_affine_wcs.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_inverse.py

This is a y6 config file that will piff from desdm.

ENH added Y6 config file and fixed caching bug

---

pizza_cutter/coadding/__init__.py
pizza_cutter/coadding/_lanczos.py
pizza_cutter/coadding/_wcs_utils.py
pizza_cutter/coadding/tests/test_wcs_utils.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_pickles.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_pixel_area.py

This PR adds
- parallel Lanczos interp w/ numba `prange`
- faster WCS area interpolant
- improved tests for WCS area interpolations

ENH more parallel code and better tests

---

pizza_cutter/slice_utils/pbar.py

This option makes the status bar flush if wanted and have a length that is a bit more predictable.

ENH add extra options to the status bar

---

pizza_cutter/des_pizza_cutter/_load_info.py

Makes the logging a bit nicer.

ENH improve the logging output

---

bin/des-pizza-cutter

This PR allows files for the output path.

ENH allow files

---

bin/des-pizza-cutter
bin/run-metadetect-on-slices
pizza_cutter/metadetect/run_metadetect.py

This PR adds support for outputting to files for running mdet.

ENH support files for mdet

---

pizza_cutter/slice_utils/interpolate.py

use np.int64 rather than numba.int64

---

pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/integration_test/data.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end.py
pizza_cutter/slice_utils/symmetrize.py
pizza_cutter/slice_utils/tests/test_symmetrize.py

This PR adds code to rotate masks by other angles.

ENH add ability to rotate by degrees

---

bin/des-pizza-cutter
pizza_cutter/coadding/tests/test_wcs_utils.py
pizza_cutter/des_pizza_cutter/_load_info.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/conftest.py
pizza_cutter/des_pizza_cutter/tests/test_sky_bounds.py
pizza_cutter/tests/test_wcs.py
pizza_cutter/wcs.py

This PR fixes a bug where WCs jacobians and/or areas are not computed correctly.

BUG make sure to wrap ra differences when computing WCS jacobians/areas

---

bin/des-pizza-cutter
pizza_cutter/des_pizza_cutter/__init__.py
pizza_cutter/des_pizza_cutter/_des_info.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end.py
pizza_cutter/des_pizza_cutter/tests/test_pizza_cutter_metadata.py

This adds the tile info in the meds file.

ENH record tile info in the metadata

---

pizza_cutter/slice_utils/interpolate.py
pizza_cutter/slice_utils/symmetrize.py
pizza_cutter/slice_utils/tests/test_interpolate.py

This PR adds an extra API and refactors the interpolant a bit to be faster.

ENH refactor interp

---

pizza_cutter/des_pizza_cutter/_constants.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end.py
pizza_cutter/des_pizza_cutter/tests/test_pizza_cutter_metadata.py

This works around a cfitsio feature where a column cannot be more than some maximum number of bytes.

BUG put tile info in new ext

---

pizza_cutter/des_pizza_cutter/_des_info.py

This PR fixes the QA checks for missing keys.

BUG fix QA check for missing keys

---

bin/des-pizza-cutter
config_files/des-pizza-slices-y6-v10.yaml
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

This PR has minor changes in configs etc to enhance FITS image handling.
We now set the dither in fpack via the image checksum. 
We have an explicit assert for negative weights or mfrac values before fpacking. Thus we will know that if we see any after, they came from the packing. 
closes #268

ENH minor fixes/improvements for fits processing

---

config_files/des-pizza-slices-y6-v10.yaml
pizza_cutter/des_pizza_cutter/_pizza_cutter.py

This PRlet's the code adapt the fpack tile size for better compression.

ENH adapt fpack tile size for better compression

---

config_files/des-pizza-slices-y6-v11.yaml
pizza_cutter/des_pizza_cutter/_piff_tools.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/integration_test/data.py

This PR enables per band piff colors and adds piff cuts. 
closes #267

ENH enable per band piff kwargs and add piff cuts to the config

---

config_files/des-pizza-slices-y6-v11.yaml
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_pizza_cutter.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/integration_test/data.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_ccd_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_map_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_pickles.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_resample.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_set_interp.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_set_psf.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_sky_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_slice_bnds.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_slice_io.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_color.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_inverse.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_jacobian.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_wcs_pixel_area.py
pizza_cutter/slice_utils/procflags.py

This PR adds flagging of piff models in bad regions.

ENH add flagging of piff models in bad regions

---

pizza_cutter/des_pizza_cutter/_constants.py

Adding the flag here per our current conventions.

ENH add flag for apodized pixels

---

config_files/des-pizza-slices-y6-v11.yaml
pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end.py

This PR tries simpler PSF cuts for Piff.

ENH try simpler PSF cuts

---

pizza_cutter/des_pizza_cutter/_piff_tools.py

Update code to use the HSM QA table.

ENH update to HSM qa

---

config_files/des-pizza-slices-y6-v12.yaml
pizza_cutter/des_pizza_cutter/_piff_tools.py
pizza_cutter/des_pizza_cutter/tests/test_piff_tools.py

This PR adds support for no cuts.

ENH support no cuts

---

config_files/des-pizza-slices-y6-v14.yaml
pizza_cutter/des_pizza_cutter/integration_test/data.py
pizza_cutter/des_pizza_cutter/integration_test/tests/test_coadding_end2end_star.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py

This PR adds an extra couple of unit tests and a new config.

TST added more unit tests

---

bin/des-pizza-cutter-prep-tile
pizza_cutter/des_pizza_cutter/__init__.py
pizza_cutter/des_pizza_cutter/_des_info.py
pizza_cutter/des_pizza_cutter/_piff_tools.py

This PR adds a coadd geom file needed by some codes.

ENH add coadd geom file

---

bin/des-pizza-cutter-prep-tile

This PR removes the geom files.

DEP remove geom files

---

pizza_cutter/des_pizza_cutter/_des_info.py
pizza_cutter/des_pizza_cutter/tests/test_des_info.py

ENH allow .fits or .fits.fz

---

bin/des-pizza-cutter

BUG do not use os.remove

---

pizza_cutter/des_pizza_cutter/_des_info.py
pizza_cutter/des_pizza_cutter/tests/test_des_info.py

This PR fixes false positive errors for empty keys when running on the sims.

BUG fix false positive error for empty keys

---

pizza_cutter/des_pizza_cutter/_coadd_slices.py
pizza_cutter/des_pizza_cutter/_load_info.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py

This PR allows the code to use astro refine headers.

ENH use astro refine

---

pizza_cutter/des_pizza_cutter/_load_info.py
pizza_cutter/des_pizza_cutter/_se_image.py
pizza_cutter/des_pizza_cutter/tests/test_build_gsobject.py

Allow eval values for input PSFs for testing.

ENH allow eval-repr for testing
